version: 2
registries:
  git-github-com:
    type: git
    url: https://github.com
    username: saminfante
    password: "${{secrets.GIT_GITHUB_COM_PASSWORD}}"

updates:
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: daily
    time: "13:49"
    timezone: US/Central
  open-pull-requests-limit: 99
  ignore:
  - dependency-name: com.amazonaws:aws-java-sdk-ec2
    versions:
    - 1.11.1000
    - 1.11.1001
    - 1.11.1002
    - 1.11.1003
    - 1.11.1004
    - 1.11.1005
    - 1.11.944
    - 1.11.945
    - 1.11.946
    - 1.11.947
    - 1.11.948
    - 1.11.949
    - 1.11.950
    - 1.11.951
    - 1.11.952
    - 1.11.953
    - 1.11.954
    - 1.11.955
    - 1.11.956
    - 1.11.957
    - 1.11.958
    - 1.11.959
    - 1.11.960
    - 1.11.961
    - 1.11.962
    - 1.11.963
    - 1.11.964
    - 1.11.965
    - 1.11.966
    - 1.11.967
    - 1.11.968
    - 1.11.969
    - 1.11.970
    - 1.11.971
    - 1.11.972
    - 1.11.973
    - 1.11.974
    - 1.11.975
    - 1.11.976
    - 1.11.977
    - 1.11.978
    - 1.11.979
    - 1.11.980
    - 1.11.981
    - 1.11.982
    - 1.11.985
    - 1.11.986
    - 1.11.987
    - 1.11.988
    - 1.11.989
    - 1.11.990
    - 1.11.991
    - 1.11.992
    - 1.11.993
    - 1.11.994
    - 1.11.995
    - 1.11.996
    - 1.11.997
    - 1.11.998
    - 1.11.999
  - dependency-name: com.amazonaws:aws-java-sdk-dynamodb
    versions:
    - 1.11.1000
    - 1.11.1001
    - 1.11.1002
    - 1.11.1003
    - 1.11.1004
    - 1.11.1005
    - 1.11.944
    - 1.11.945
    - 1.11.946
    - 1.11.947
    - 1.11.948
    - 1.11.949
    - 1.11.950
    - 1.11.951
    - 1.11.952
    - 1.11.953
    - 1.11.954
    - 1.11.955
    - 1.11.956
    - 1.11.957
    - 1.11.958
    - 1.11.959
    - 1.11.960
    - 1.11.961
    - 1.11.962
    - 1.11.963
    - 1.11.964
    - 1.11.965
    - 1.11.966
    - 1.11.967
    - 1.11.968
    - 1.11.969
    - 1.11.970
    - 1.11.971
    - 1.11.972
    - 1.11.973
    - 1.11.974
    - 1.11.975
    - 1.11.976
    - 1.11.977
    - 1.11.978
    - 1.11.979
    - 1.11.980
    - 1.11.981
    - 1.11.982
    - 1.11.985
    - 1.11.986
    - 1.11.987
    - 1.11.988
    - 1.11.989
    - 1.11.990
    - 1.11.991
    - 1.11.992
    - 1.11.993
    - 1.11.994
    - 1.11.995
    - 1.11.996
    - 1.11.997
    - 1.11.998
    - 1.11.999
  - dependency-name: com.amazonaws:aws-java-sdk-core
    versions:
    - 1.11.1000
    - 1.11.1001
    - 1.11.1002
    - 1.11.1003
    - 1.11.1004
    - 1.11.1005
    - 1.11.944
    - 1.11.945
    - 1.11.946
    - 1.11.947
    - 1.11.948
    - 1.11.949
    - 1.11.950
    - 1.11.951
    - 1.11.952
    - 1.11.953
    - 1.11.954
    - 1.11.955
    - 1.11.956
    - 1.11.957
    - 1.11.958
    - 1.11.959
    - 1.11.960
    - 1.11.961
    - 1.11.962
    - 1.11.963
    - 1.11.964
    - 1.11.965
    - 1.11.966
    - 1.11.967
    - 1.11.968
    - 1.11.969
    - 1.11.970
    - 1.11.971
    - 1.11.972
    - 1.11.973
    - 1.11.974
    - 1.11.975
    - 1.11.976
    - 1.11.977
    - 1.11.978
    - 1.11.979
    - 1.11.980
    - 1.11.981
    - 1.11.982
    - 1.11.985
    - 1.11.986
    - 1.11.987
    - 1.11.988
    - 1.11.989
    - 1.11.990
    - 1.11.991
    - 1.11.992
    - 1.11.993
    - 1.11.994
    - 1.11.995
    - 1.11.996
    - 1.11.997
    - 1.11.998
    - 1.11.999
  - dependency-name: io.netty:netty-transport-native-epoll:linux-x86_64
    versions:
    - 4.1.58.Final
    - 4.1.59.Final
    - 4.1.60.Final
    - 4.1.61.Final
    - 4.1.62.Final
  - dependency-name: io.netty:netty-buffer
    versions:
    - 4.1.58.Final
    - 4.1.59.Final
    - 4.1.60.Final
    - 4.1.61.Final
    - 4.1.62.Final
  - dependency-name: io.netty:netty-common
    versions:
    - 4.1.58.Final
    - 4.1.59.Final
    - 4.1.60.Final
    - 4.1.61.Final
    - 4.1.62.Final
  - dependency-name: io.netty:netty-transport
    versions:
    - 4.1.58.Final
    - 4.1.59.Final
    - 4.1.60.Final
    - 4.1.61.Final
    - 4.1.62.Final
  - dependency-name: io.netty:netty-codec
    versions:
    - 4.1.58.Final
    - 4.1.59.Final
    - 4.1.60.Final
    - 4.1.61.Final
    - 4.1.62.Final
  - dependency-name: io.netty:netty-handler
    versions:
    - 4.1.58.Final
    - 4.1.59.Final
    - 4.1.60.Final
    - 4.1.61.Final
    - 4.1.62.Final
  - dependency-name: io.netty:netty-codec-http2
    versions:
    - 4.1.58.Final
    - 4.1.59.Final
    - 4.1.60.Final
    - 4.1.61.Final
    - 4.1.62.Final
  - dependency-name: io.netty:netty-codec-http
    versions:
    - 4.1.58.Final
    - 4.1.59.Final
    - 4.1.60.Final
    - 4.1.61.Final
    - 4.1.62.Final
  - dependency-name: io.netty:netty-tcnative-boringssl-static
    versions:
    - 2.0.36.Final
    - 2.0.38.Final
  - dependency-name: com.github.spotbugs:spotbugs-maven-plugin
    versions:
    - 4.2.0
    - 4.2.2
  - dependency-name: com.fasterxml.jackson.core:jackson-annotations
    versions:
    - 2.12.1
    - 2.12.2
  - dependency-name: com.fasterxml.jackson.datatype:jackson-datatype-jsr310
    versions:
    - 2.12.1
    - 2.12.2
  - dependency-name: com.fasterxml.jackson.datatype:jackson-datatype-jdk8
    versions:
    - 2.12.1
    - 2.12.2
  - dependency-name: com.fasterxml.jackson.jr:jackson-jr-objects
    versions:
    - 2.12.1
    - 2.12.2
  - dependency-name: com.fasterxml.jackson.dataformat:jackson-dataformat-cbor
    versions:
    - 2.12.1
    - 2.12.2
  - dependency-name: com.fasterxml.jackson.core:jackson-core
    versions:
    - 2.12.1
    - 2.12.2
  - dependency-name: com.fasterxml.jackson.core:jackson-databind
    versions:
    - 2.12.1
    - 2.12.2
  - dependency-name: org.openjdk.jmh:jmh-generator-annprocess
    versions:
    - "1.27"
    - "1.28"
  - dependency-name: org.openjdk.jmh:jmh-core
    versions:
    - "1.27"
    - "1.28"
  - dependency-name: nl.jqno.equalsverifier:equalsverifier
    versions:
    - 3.5.2
    - 3.5.3
    - 3.5.4
    - 3.5.5
  - dependency-name: org.mockito:mockito-core
    versions:
    - 3.7.7
    - 3.8.0
  - dependency-name: org.eclipse.jetty:jetty-bom
    versions:
    - 11.0.0
    - 11.0.1
  - dependency-name: io.reactivex.rxjava2:rxjava
    versions:
    - 2.2.20
  - dependency-name: org.apache.commons:commons-lang3
    versions:
    - "3.11"
  - dependency-name: org.eclipse.jdt:org.eclipse.jdt.core
    versions:
    - 3.24.0
  - dependency-name: org.apache.maven.plugins:maven-checkstyle-plugin
    versions:
    - 3.1.1
  - dependency-name: org.apache.maven:maven-plugin-api
    versions:
    - 3.6.3
  - dependency-name: org.apache.maven.plugin-tools:maven-plugin-annotations
    versions:
    - 3.6.0
  - dependency-name: org.apache.maven.plugins:maven-plugin-plugin
    versions:
    - 3.6.0
  registries:
  - git-github-com
